#import "./ImageFragment.gql"
#import "./VideoFragment.gql"

fragment ExhibitionFragmentLight on ExhibitionRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	endDate
	image {
		...ImageThumbnailFragment
	}
	year {
		id
		title
	}
	location {
		id
		title
	}
	slug
}
