query Menu($yearId: ItemId) {
	abouts: allAbouts(
		filter: { OR: [{ year: { eq: $yearId } }, { year: { exists: false } }] }

		first: 100
	) {
		id
		title
		slug
		year {
			title
		}
	}
	years: allYears(
		filter: { id: { neq: $yearId } }

		first: 100
		orderBy: title_DESC
	) {
		...YearFragment
	}
	year(filter: { id: { eq: $yearId } }, orderBy: title_DESC) {
		id
		title
	}
	aboutMeta: _allAboutsMeta(filter: { year: { eq: $yearId } }) {
		count
	}
	programMeta: _allProgramsMeta(filter: { year: { eq: $yearId } }) {
		count
	}
	participantsMeta: _allParticipantsMeta(filter: { year: { eq: $yearId } }) {
		count
	}
	partnersMeta: _allPartnersMeta(filter: { year: { eq: $yearId } }) {
		count
	}
	exhibitionsMeta: _allExhibitionsMeta(filter: { year: { eq: $yearId } }) {
		count
	}
	locationsMeta: _allLocationsMeta(filter: { year: { eq: $yearId } }) {
		count
	}
}
