query AllPartners($yearId: ItemId) {
	partners: allPartners(filter: { year: { eq: $yearId } }, first: 100) {
		...PartnerFragmentLight
	}
	pagination: _allPartnersMeta {
		count
	}
}

query Partner($slug: String!) {
	partner(filter: { slug: { eq: $slug } }) {
		...PartnerFragment
	}
}
