query AllPrograms($yearId: ItemId) {
	programs: allPrograms(
		filter: { year: { eq: $yearId } }
		orderBy: [startDate_ASC, startTime_ASC]
		first: 100
	) {
		...ProgramFragmentLight
	}
	pagination: _allProgramsMeta {
		count
	}
}

query Program($slug: String!) {
	program(filter: { slug: { eq: $slug } }) {
		...ProgramFragment
	}
}

query AllProgramCategories {
	programCategories: allProgramCategories(orderBy: title_DESC, first: 100) {
		id
		title
		desc
	}
}
